import { useEffect, useState } from 'react';
import { History, Search } from 'lucide-react';
import { useParams } from 'react-router-dom';
import { supabase } from '../lib/supabase';
import { Page } from '../components/Layout';
import { Empty, Center } from '../components/ui';
import { useSeason } from '../hooks/useSeason';
import { dateTime } from '../lib/utils';

const labels: Record<string,string> = { players:'giocatore', sessions:'seduta', matches:'partita', match_callups:'convocazione', match_player_stats:'minutaggio', match_events:'evento partita', attendance_records:'presenza', player_session_loads:'carico', training_games:'partitella', training_game_players:'giocatori partitella', training_game_goals:'gol partitella', leaderboard_penalties:'penalità classifica', fine_types:'tipologia multa', fines:'multa', fine_payments:'pagamento multa', season_members:'membro staff', season_access_requests:'richiesta accesso', season_settings:'impostazioni', programmed_absences:'assenza programmata', callup_status_options:'stato convocazione', player_access_tokens:'link giocatore' };
const verbs: Record<string,string> = { INSERT:'ha creato', UPDATE:'ha modificato', DELETE:'ha eliminato' };
export default function Logs(){const{seasonId}=useParams(),{season,loading}=useSeason(seasonId),[rows,setRows]=useState<any[]>([]),[q,setQ]=useState('');useEffect(()=>{if(!seasonId)return;supabase.from('activity_logs').select('*,profiles:actor_user_id(full_name,email)').eq('season_id',seasonId).order('created_at',{ascending:false}).limit(500).then(({data})=>setRows(data||[]))},[seasonId]);const filtered=rows.filter(x=>`${x.action} ${x.entity_type} ${x.profiles?.full_name||''} ${JSON.stringify(x.metadata||{})}`.toLowerCase().includes(q.toLowerCase()));if(loading||!season)return <Center/>;return <Page season={season} title="Log attività" sub="Storico completo delle modifiche registrate dal database"><div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Cerca azione, elemento, utente…" value={q} onChange={e=>setQ(e.target.value)}/></div></div>{filtered.length?<div className="cards">{filtered.map(x=>{const actor=x.profiles?.full_name||x.profiles?.email||'Sistema';const entity=labels[x.entity_type]||x.entity_type||'elemento';return <div className="info" key={x.id}><div><b>{actor} {verbs[x.action]||x.action.toLowerCase()} {entity}</b><small>{dateTime(x.created_at)}{x.entity_id?` · ID ${x.entity_id}`:''}</small>{x.metadata&&x.metadata.source&&<small>Origine: {x.metadata.source}</small>}</div><History size={17}/></div>})}</div>:<Empty title="Nessun log" text="Le operazioni importanti vengono registrate automaticamente."/>}</Page>}
