import{useEffect,useMemo,useState}from'react';import{Archive,Edit3,ExternalLink,Link2,Plus,RotateCcw,Search,Trash2,Copy,BarChart3,Users,UserRound}from'lucide-react';import{useNavigate,useParams}from'react-router-dom';import{supabase}from'../lib/supabase';import{hash,rand,initials,date}from'../lib/utils';import{Player}from'../types';import{Confirm,Empty,Modal,Center}from'../components/ui';import{Page}from'../components/Layout';import{useSeason}from'../hooks/useSeason';import{useToast}from'../components/Toast';
const blank={first_name:'',last_name:'',shirt_number:'',position:'',document_type:'',document_number:'',birth_date:'',notes:''};
const staffBlank={first_name:'',last_name:'',role:'HEAD_COACH',phone:'',notes:''};
const staffRoleLabels:any={HEAD_COACH:'Allenatore',ASSISTANT_COACH:'Vice allenatore',FITNESS_COACH:'Preparatore atletico',GOALKEEPER_COACH:'Preparatore portieri',TECHNICAL_COLLABORATOR:'Collaboratore tecnico',TEAM_MANAGER:'Dirigente accompagnatore',OTHER:'Altro'};
export default function Players(){const{seasonId}=useParams(),{season,loading}=useSeason(seasonId),toast=useToast(),nav=useNavigate();const[players,setPlayers]=useState<Player[]>([]),[trash,setTrash]=useState<Player[]>([]),[q,setQ]=useState(''),[modal,setModal]=useState(false),[editing,setEditing]=useState<Player|null>(null),[form,setForm]=useState(blank),[confirm,setConfirm]=useState<{kind:'archive'|'delete'|'restore';player:Player}|null>(null),[portalUrl,setPortalUrl]=useState<string|null>(null),[trashOpen,setTrashOpen]=useState(false),[busy,setBusy]=useState(false),[tab,setTab]=useState<'players'|'staff'>('players');
const[staff,setStaff]=useState<any[]>([]),[staffTrash,setStaffTrash]=useState<any[]>([]),[staffModal,setStaffModal]=useState(false),[staffEditing,setStaffEditing]=useState<any|null>(null),[staffForm,setStaffForm]=useState(staffBlank),[staffConfirm,setStaffConfirm]=useState<any|null>(null),[staffTrashOpen,setStaffTrashOpen]=useState(false);
async function load(){if(!seasonId)return;const{data,error}=await supabase.from('players').select('*').eq('season_id',seasonId).order('last_name').order('first_name');if(error){toast.push(error.message,'error');return}const all=(data||[]) as Player[];setPlayers(all.filter(p=>p.status==='ACTIVE'));setTrash(all.filter(p=>p.status==='ARCHIVED'));
const{data:sdata,error:serror}=await supabase.from('technical_staff').select('*').eq('season_id',seasonId).order('last_name').order('first_name');
if(serror)toast.push(serror.message,'error'); else {setStaff((sdata||[]).filter((x:any)=>x.status==='ACTIVE'));setStaffTrash((sdata||[]).filter((x:any)=>x.status==='ARCHIVED'))}
}useEffect(()=>{load()},[seasonId]);const filtered=useMemo(()=>players.filter(p=>`${p.first_name} ${p.last_name}`.toLowerCase().includes(q.toLowerCase())||String(p.shirt_number||'').includes(q)),[players,q]);
function openNew(){setEditing(null);setForm({...blank});setModal(true)}function openEdit(p:Player){setEditing(p);setForm({first_name:p.first_name,last_name:p.last_name,shirt_number:p.shirt_number?String(p.shirt_number):'',position:p.position||'',document_type:p.document_type||'',document_number:p.document_number||'',birth_date:p.birth_date||'',notes:p.notes||''});setModal(true)}
async function save(e:React.FormEvent){e.preventDefault();if(!seasonId)return;setBusy(true);const payload={season_id:seasonId,first_name:form.first_name.trim(),last_name:form.last_name.trim(),shirt_number:form.shirt_number?Number(form.shirt_number):null,position:form.position.trim()||null,document_type:form.document_type.trim()||null,document_number:form.document_number.trim()||null,birth_date:form.birth_date||null,notes:form.notes.trim()||null,status:'ACTIVE'};const res=editing?await supabase.from('players').update(payload).eq('id',editing.id):await supabase.from('players').insert(payload);if(res.error)toast.push(res.error.message,'error');else{toast.push(editing?'Giocatore aggiornato':'Giocatore aggiunto');setModal(false);setEditing(null);setForm({...blank});await load()}setBusy(false)}
async function doArchive(){if(!confirm)return;setBusy(true);const{error}=await supabase.from('players').update({status:'ARCHIVED',archived_at:new Date().toISOString()}).eq('id',confirm.player.id);if(error)toast.push(error.message,'error');else{toast.push('Giocatore archiviato');await load()}setBusy(false);setConfirm(null)}
async function doRestore(){if(!confirm)return;setBusy(true);const{error}=await supabase.from('players').update({status:'ACTIVE',archived_at:null}).eq('id',confirm.player.id);if(error)toast.push(error.message,'error');else{toast.push('Giocatore ripristinato');await load()}setBusy(false);setConfirm(null)}
async function doDelete(){if(!confirm||!seasonId)return;setBusy(true);const{data,error}=await supabase.rpc('hard_delete_player',{p_id:confirm.player.id});if(error||data===false){toast.push(error?.message||'Il giocatore ha dati storici e non può essere eliminato definitivamente.','error')}else{toast.push('Giocatore eliminato definitivamente');await load()}setBusy(false);setConfirm(null)}
async function playerLink(p:Player){setBusy(true);const raw=rand(),h=await hash(raw);await supabase.from('player_access_tokens').update({revoked_at:new Date().toISOString()}).eq('player_id',p.id).is('revoked_at',null);const{error}=await supabase.from('player_access_tokens').insert({player_id:p.id,token_hash:h});if(error)toast.push(error.message,'error');else{const url=`${location.origin}${location.pathname}#/player/${raw}`;await navigator.clipboard?.writeText(url);setPortalUrl(url);toast.push('Link personale generato e copiato')}setBusy(false)}

function openStaff(s:any=null){setStaffEditing(s);setStaffForm(s?{first_name:s.first_name,last_name:s.last_name,role:s.role,phone:s.phone||'',notes:s.notes||''}:{...staffBlank});setStaffModal(true)}
async function saveStaff(e:React.FormEvent){e.preventDefault();if(!seasonId)return;setBusy(true);const payload={season_id:seasonId,first_name:staffForm.first_name.trim(),last_name:staffForm.last_name.trim(),role:staffForm.role,phone:staffForm.phone.trim()||null,notes:staffForm.notes.trim()||null,status:'ACTIVE'};const res=staffEditing?await supabase.from('technical_staff').update(payload).eq('id',staffEditing.id):await supabase.from('technical_staff').insert(payload);if(res.error)toast.push(res.error.message,'error');else{toast.push(staffEditing?'Staff aggiornato':'Membro dello staff aggiunto');setStaffModal(false);setStaffEditing(null);await load()}setBusy(false)}
async function archiveStaff(){if(!staffConfirm)return;setBusy(true);const{error}=await supabase.from('technical_staff').update({status:'ARCHIVED',archived_at:new Date().toISOString()}).eq('id',staffConfirm.id);if(error)toast.push(error.message,'error');else await load();setBusy(false);setStaffConfirm(null)}
async function restoreStaff(){if(!staffConfirm)return;setBusy(true);const{error}=await supabase.from('technical_staff').update({status:'ACTIVE',archived_at:null}).eq('id',staffConfirm.id);if(error)toast.push(error.message,'error');else await load();setBusy(false);setStaffConfirm(null)}
if(loading||!season)return <Center/>;
return <Page season={season} title="Rosa" sub={tab==='players'?`${players.length} giocatori attivi · gli archiviati restano nello storico`:`${staff.length} membri staff attivi · presenze gestite nelle sedute`}
 actions={tab==='players'?<><button className="secondary" onClick={()=>setTrashOpen(true)}><Trash2/>Cestino ({trash.length})</button><button className="primary" onClick={openNew}><Plus/>Nuovo giocatore</button></>:<><button className="secondary" onClick={()=>setStaffTrashOpen(true)}><Trash2/>Archivio ({staffTrash.length})</button><button className="primary" onClick={()=>openStaff()}><Plus/>Nuovo staff</button></>}>
 <div className="section-tabs" role="tablist">
  <button className={tab==='players'?'active':''} onClick={()=>setTab('players')}><Users/>Giocatori <small>{players.length}</small></button>
  <button className={tab==='staff'?'active':''} onClick={()=>setTab('staff')}><UserRound/>Staff tecnico <small>{staff.length}</small></button>
 </div>
 {tab==='players'&&<><div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Cerca nome, numero…" value={q} onChange={e=>setQ(e.target.value)}/></div></div>{filtered.length?<div className="player-grid">{filtered.map(p=><article className="player-card" key={p.id}><div className="player-main"><div className="avatar">{initials(p.first_name,p.last_name)}</div><div><h3>{p.first_name} {p.last_name}</h3><p>{p.position||'Ruolo non specificato'} {p.shirt_number?`· #${p.shirt_number}`:''}</p></div></div><div className="player-actions"><button className="icon" title="Profilo" onClick={()=>nav(`/season/${seasonId}/players/${p.id}`)}><BarChart3 size={17}/></button><button className="icon" title="Modifica" onClick={()=>openEdit(p)}><Edit3 size={17}/></button><button className="icon" title="Link personale" onClick={()=>playerLink(p)}><Link2 size={17}/></button><button className="icon warning" title="Archivia" onClick={()=>setConfirm({kind:'archive',player:p})}><Archive size={17}/></button><button className="icon danger-icon" title="Elimina definitivamente" onClick={()=>setConfirm({kind:'delete',player:p})}><Trash2 size={17}/></button></div></article>)}</div>:<Empty title="Nessun giocatore" text="Aggiungi il primo giocatore alla rosa." action="Nuovo giocatore" click={openNew}/>}</>}
 {tab==='staff'&&<><div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Cerca nome o ruolo…" value={q} onChange={e=>setQ(e.target.value)}/></div></div>{staff.filter(s=>`${s.first_name} ${s.last_name} ${staffRoleLabels[s.role]}`.toLowerCase().includes(q.toLowerCase())).length?<div className="player-grid">{staff.filter(s=>`${s.first_name} ${s.last_name} ${staffRoleLabels[s.role]}`.toLowerCase().includes(q.toLowerCase())).map(s=><article className="player-card" key={s.id}><div className="player-main"><div className="avatar">{initials(s.first_name,s.last_name)}</div><div><h3>{s.first_name} {s.last_name}</h3><p>{staffRoleLabels[s.role]}{s.phone?` · ${s.phone}`:''}</p></div></div><div className="player-actions"><button className="icon" title="Modifica" onClick={()=>openStaff(s)}><Edit3 size={17}/></button><button className="icon warning" title="Archivia" onClick={()=>setStaffConfirm(s)}><Archive size={17}/></button></div></article>)}</div>:<Empty title="Nessuno staff" text="Aggiungi allenatore, vice, preparatore o dirigente." action="Nuovo staff" click={()=>openStaff()}/>}</>}
 {staffModal&&<Modal title={staffEditing?'Modifica staff':'Nuovo staff'} close={()=>setStaffModal(false)}><form className="form" onSubmit={saveStaff}><div className="form-grid"><label>Nome<input required autoFocus value={staffForm.first_name} onChange={e=>setStaffForm({...staffForm,first_name:e.target.value})}/></label><label>Cognome<input required value={staffForm.last_name} onChange={e=>setStaffForm({...staffForm,last_name:e.target.value})}/></label><label>Ruolo<select value={staffForm.role} onChange={e=>setStaffForm({...staffForm,role:e.target.value})}>{Object.entries(staffRoleLabels).map(([k,v])=><option key={k} value={k}>{v as string}</option>)}</select></label><label>Telefono<input value={staffForm.phone} onChange={e=>setStaffForm({...staffForm,phone:e.target.value})}/></label></div><label>Note<textarea value={staffForm.notes} onChange={e=>setStaffForm({...staffForm,notes:e.target.value})}/></label><button className="primary wide" disabled={busy}>{busy?'Salvataggio…':'Salva staff'}</button></form></Modal>}
 {staffTrashOpen&&<Modal title="Archivio staff" close={()=>setStaffTrashOpen(false)}><p className="muted">Lo staff archiviato mantiene lo storico delle presenze.</p>{staffTrash.length?<div className="cards">{staffTrash.map(s=><div className="info" key={s.id}><div><b>{s.first_name} {s.last_name}</b><small>{staffRoleLabels[s.role]}</small></div><button className="small" onClick={()=>{setStaffConfirm({...s,__restore:true});setStaffTrashOpen(false)}}><RotateCcw size={14}/>Ripristina</button></div>)}</div>:<Empty title="Archivio vuoto" text="Nessun membro staff archiviato."/>}</Modal>}
 {staffConfirm&&<Confirm title={staffConfirm.__restore?'Ripristinare lo staff?':'Archiviare lo staff?'} text={staffConfirm.__restore?'Tornerà disponibile per le nuove sedute.':'Sparirà dallo staff attivo ma conserverà lo storico.'} confirmLabel={staffConfirm.__restore?'Ripristina':'Archivia'} onClose={()=>setStaffConfirm(null)} onConfirm={staffConfirm.__restore?restoreStaff:archiveStaff} busy={busy}/>}
 {modal&&<Modal title={editing?'Modifica giocatore':'Nuovo giocatore'} close={()=>{setModal(false);setEditing(null);setForm({...blank})}}><form className="form" onSubmit={save}><div className="form-grid"><label>Nome<input autoFocus required value={form.first_name} onChange={e=>setForm({...form,first_name:e.target.value})}/></label><label>Cognome<input required value={form.last_name} onChange={e=>setForm({...form,last_name:e.target.value})}/></label><label>Numero<input type="number" min="1" max="99" value={form.shirt_number} onChange={e=>setForm({...form,shirt_number:e.target.value})}/></label><label>Ruolo<input placeholder="Es. Portiere" value={form.position} onChange={e=>setForm({...form,position:e.target.value})}/></label><label>Data di nascita<input type="date" value={form.birth_date} onChange={e=>setForm({...form,birth_date:e.target.value})}/></label><label>Tipo documento<select value={form.document_type} onChange={e=>setForm({...form,document_type:e.target.value})}><option value="">Non specificato</option><option>Carta d'identità</option><option>Passaporto</option><option>Patente</option><option>Permesso di soggiorno</option><option>Altro</option></select></label><label>Numero documento<input value={form.document_number} onChange={e=>setForm({...form,document_number:e.target.value})}/></label></div><label>Note<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="primary wide" disabled={busy}>{busy?'Salvataggio…':editing?'Salva modifiche':'Aggiungi giocatore'}</button></form></Modal>}
 {portalUrl&&<Modal title="Link personale" close={()=>setPortalUrl(null)}><p className="muted">Il link è un token casuale non prevedibile. Generandone uno nuovo, il precedente viene revocato.</p><div className="link-box">{portalUrl}</div><button className="secondary wide" onClick={()=>navigator.clipboard?.writeText(portalUrl)}><Copy/>Copia link</button></Modal>}
 {confirm?.kind==='archive'&&<Confirm title="Archiviare il giocatore?" text={`${confirm.player.first_name} ${confirm.player.last_name} sparirà dalla rosa attiva ma conserverà tutto lo storico.`} confirmLabel="Archivia" onClose={()=>setConfirm(null)} onConfirm={doArchive} busy={busy}/>}
 {confirm?.kind==='restore'&&<Confirm title="Ripristinare il giocatore?" text="Tornerà nella rosa attiva e sarà disponibile per le nuove sedute." confirmLabel="Ripristina" onClose={()=>setConfirm(null)} onConfirm={doRestore} busy={busy}/>}
 {confirm?.kind==='delete'&&<Confirm title="Eliminare definitivamente?" text="L’eliminazione definitiva è consentita solo se non esistono dati storici collegati." confirmLabel="Elimina definitivamente" danger onClose={()=>setConfirm(null)} onConfirm={doDelete} busy={busy}/>}
 {trashOpen&&<Modal title="Cestino della rosa" close={()=>setTrashOpen(false)} wide><p className="muted">Gli archiviati mantengono tutto lo storico.</p>{trash.length?<div className="cards">{trash.map(p=><div className="info" key={p.id}><div><b>{p.first_name} {p.last_name}</b><small>Archiviato {p.archived_at?date(p.archived_at):'—'}</small></div><div className="row-actions"><button className="small" onClick={()=>{setConfirm({kind:'restore',player:p});setTrashOpen(false)}}><RotateCcw size={14}/>Ripristina</button><button className="small danger" onClick={()=>{setConfirm({kind:'delete',player:p});setTrashOpen(false)}}><Trash2 size={14}/>Elimina definitivamente</button></div></div>)}</div>:<Empty title="Cestino vuoto" text="Nessun giocatore archiviato."/>}</Modal>}
 </Page>
}