import { useEffect, useMemo, useState } from 'react';
import { Activity, CalendarDays, CheckCircle2, Download, ShieldAlert, Trophy, Clock3, CircleDollarSign, TrendingUp, TrendingDown, Info } from 'lucide-react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { useParams } from 'react-router-dom';
import { supabase } from '../lib/supabase';
import { hash, date, money, isoDate } from '../lib/utils';
import { makePdf } from '../lib/pdf';
import { Center, Stat, Empty } from '../components/ui';

export default function PlayerPortal() {
  const { token } = useParams(), [data, setData] = useState<any>(null), [invalid, setInvalid] = useState(false);
  const [from, setFrom] = useState(''), [to, setTo] = useState(isoDate()), [preset, setPreset] = useState('CUSTOM');
  useEffect(() => { (async () => { if (!token) return; const h = await hash(token); const { data: x, error } = await supabase.rpc('player_portal_data', { h }); if (error || !x) { setInvalid(true); return; } setData(x); })(); }, [token]);
  const setRange = (value: string) => { const end = isoDate(); setPreset(value); if (value === 'SEASON') { setFrom(''); setTo(end); } else if (value === 'WEEK') { const d = new Date(); d.setDate(d.getDate() - 6); setFrom(isoDate(d)); setTo(end); } else if (value === 'MONTH') { const d = new Date(); d.setDate(1); setFrom(isoDate(d)); setTo(end); } else setFrom(''); };
  const inPeriod = (d: string) => (!from || d >= from) && (!to || d <= to);
  const loads = (data?.loads || []).filter((x: any) => inPeriod(x.session_date));
  const matches = (data?.matches || []).filter((x: any) => inPeriod(x.session_date));
  const attendance = (data?.attendance || []).filter((x: any) => inPeriod(x.session_date));
  const fines = (data?.fines || []).filter((x: any) => inPeriod(String(x.issued_at).slice(0, 10)));
  const p = data?.player;
  const yoyo = data?.yoyo || [];
  const latestYoyo = yoyo[0];
  const mins = matches.reduce((a: number, x: any) => a + (Number(x.minutes_played) || 0), 0), goals = matches.reduce((a: number, x: any) => a + (Number(x.goals) || 0), 0), totalLoad = loads.reduce((a: number, x: any) => a + (Number(x.load) || 0), 0), totalDuration = loads.reduce((a: number, x: any) => a + (Number(x.duration_minutes) || 0), 0);
  const rpeValues = loads.filter((x: any) => x.rpe != null).map((x: any) => Number(x.rpe));
  const avgRpe = rpeValues.length ? (rpeValues.reduce((a: number, b: number) => a + b, 0) / rpeValues.length).toFixed(1) : '—';
  const chart = useMemo(() => { const m = new Map<string, number>(); for (const x of loads) m.set(x.session_date, (m.get(x.session_date) || 0) + (Number(x.load) || 0)); return [...m.entries()].sort().map(([d, l]) => ({ date: date(d), load: l })); }, [loads]);
  const baselineDays = Number(data?.settings?.insight_baseline_days || 28);
  const recent7 = (data?.loads || []).filter((x: any) => { const d = new Date(); d.setDate(d.getDate() - 6); return x.session_date >= isoDate(d) && x.session_date <= isoDate(); });
  const baseStart = new Date(); baseStart.setDate(baseStart.getDate() - baselineDays - 7);
  const baseEnd = new Date(); baseEnd.setDate(baseEnd.getDate() - 7);
  const baselineLoads = (data?.loads || []).filter((x: any) => x.session_date >= isoDate(baseStart) && x.session_date < isoDate(baseEnd));
  const r7 = recent7.reduce((a: number, x: any) => a + (Number(x.load) || 0), 0), baselineTotal = baselineLoads.reduce((a: number, x: any) => a + (Number(x.load) || 0), 0), expected7 = baselineLoads.length ? baselineTotal / baselineDays * 7 : 0, delta = expected7 ? Math.round((r7 - expected7) / expected7 * 100) : null;
  const insight = delta == null ? { tone: 'neutral', title: 'Baseline individuale insufficiente', interpretation: 'Non ci sono abbastanza dati nel periodo di riferimento impostato.', attention: 'Il singolo dato non va interpretato isolatamente.', suggestion: 'Continua a registrare RPE e durata con continuità.' } : delta > 0 ? { tone: 'up', title: `Carico recente +${delta}% rispetto alla baseline`, interpretation: `Gli ultimi 7 giorni sono superiori del ${delta}% rispetto al riferimento individuale.`, attention: 'La variazione descrive il carico e non determina da sola rischio o necessità di scarico.', suggestion: 'Verifica programmazione, RPE, durata e risposta del giocatore prima di aumentare ulteriormente il carico.' } : delta < 0 ? { tone: 'down', title: `Carico recente ${delta}% rispetto alla baseline`, interpretation: `Gli ultimi 7 giorni sono inferiori del ${Math.abs(delta)}% rispetto al riferimento individuale.`, attention: 'Una riduzione non è automaticamente positiva o negativa.', suggestion: 'Leggi il dato insieme a calendario, minutaggio e obiettivi della settimana.' } : { tone: 'neutral', title: 'Carico recente vicino alla baseline', interpretation: 'Il carico degli ultimi 7 giorni è vicino al riferimento individuale.', attention: 'Il confronto resta descrittivo e dipende dalla qualità dei dati registrati.', suggestion: 'Mantieni la registrazione coerente per seguire il trend nel tempo.' };
  function pdf() { if (!p) return; makePdf(`Profilo · ${p.first_name} ${p.last_name}`, [{ title: 'Periodo', lines: [`${from || 'Inizio stagione'} → ${to || 'oggi'}`] }, { title: 'Statistiche', lines: [`Partite: ${matches.length}`, `Minuti: ${mins}`, `Gol: ${goals}`, `Carico: ${Math.round(totalLoad)} AU`, `Durata: ${totalDuration} min`, `RPE medio: ${avgRpe}`, latestYoyo ? `Ultimo Yo-Yo IR1: ${latestYoyo.distance_m} m${latestYoyo.final_level ? ` · Livello ${latestYoyo.final_level}` : ''}` : '', data.leaderboard && !from && !to ? `Punti partitelle: ${data.leaderboard.final_points} (stagione)` : ''] }, { title: 'Insight carico', lines: [insight.title, insight.interpretation, `Attenzione: ${insight.attention}`, `Suggerimento: ${insight.suggestion}`] }, { title: 'Partite', lines: matches.map((m: any) => `${date(m.session_date)} · ${m.opponent} · ${m.venue === 'HOME' ? 'Casa' : 'Trasferta'} · ${m.minutes_played}' · ${m.goals} gol · ${m.custom_status || m.callup_status || 'Non indicato'}`) }, { title: 'Carichi', lines: loads.map((x: any) => `${date(x.session_date)} · RPE ${x.rpe ?? '—'} × ${x.duration_minutes}' = ${x.load ?? 0} AU`) }, { title: 'Presenze', lines: attendance.map((x: any) => `${date(x.session_date)} · ${x.status}${x.absence_reason ? ` · ${x.absence_reason}` : ''}`) }, { title: 'Multe', lines: fines.map((x: any) => `${money(Number(x.amount))} · pagato ${money(Number(x.paid))} · residuo ${money(Number(x.residual))}`) }], 'profilo-giocatore.pdf', { team: data.season?.team_name, season: data.season?.sporting_year }); }
  if (invalid) return <div className="center"><ShieldAlert /><h2>Link non valido o revocato</h2><p className="muted">Chiedi all’allenatore di generare un nuovo link.</p></div>;
  if (!data) return <Center text="Caricamento profilo…" />;
  return <div className="portal"><header className="portal-top"><i>S</i><b>SOCCERMRGAMIFICATION</b><span className="muted">{data.season?.team_name || ''}</span></header><div className="portal-page"><small>PLAYER PORTAL</small><h1>{p.first_name} {p.last_name}</h1><p>{data.season?.sporting_year || ''} · I tuoi dati personali della stagione.</p>
    <div className="segmented tabs"><button className={preset === 'WEEK' ? 'active' : ''} onClick={() => setRange('WEEK')}>Settimana</button><button className={preset === 'MONTH' ? 'active' : ''} onClick={() => setRange('MONTH')}>Mese</button><button className={preset === 'SEASON' ? 'active' : ''} onClick={() => setRange('SEASON')}>Stagione</button><button className={preset === 'CUSTOM' ? 'active' : ''} onClick={() => setRange('CUSTOM')}>Personalizzato</button></div>
    <div className="filters"><input type="date" value={from} onChange={e => { setPreset('CUSTOM'); setFrom(e.target.value); }} /><input type="date" value={to} onChange={e => { setPreset('CUSTOM'); setTo(e.target.value); }} /><button className="primary" onClick={pdf}><Download />Scarica PDF</button></div>
    <div className="stats"><Stat label="Partite" value={matches.length} icon={<Trophy />} /><Stat label="Minuti" value={mins} icon={<CalendarDays />} /><Stat label="Gol" value={goals} icon={<Trophy />} /><Stat label="Carico" value={`${Math.round(totalLoad)} AU`} icon={<Activity />} /></div>
    <div className="stats"><Stat label="Durata" value={`${totalDuration} min`} icon={<Clock3 />} /><Stat label="RPE medio" value={avgRpe} icon={<Activity />} /><Stat label="Presenze" value={attendance.filter((x: any) => x.status === 'PRESENT').length} icon={<CheckCircle2 />} /><Stat label="Multe residue" value={money(fines.reduce((a: number, x: any) => a + Number(x.residual || 0), 0))} icon={<CircleDollarSign />} /></div>
    <section><div className="insight"><Info /> <div><b>{insight.title}</b><p>{insight.interpretation}</p><p><strong>Attenzione:</strong> {insight.attention}</p><p><strong>Suggerimento:</strong> {insight.suggestion}</p><p className="muted">Gli insight non sono soglie cliniche e non stimano il rischio di infortunio. Servono a leggere i dati di carico in modo prudente.</p></div>{insight.tone === 'up' ? <TrendingUp /> : insight.tone === 'down' ? <TrendingDown /> : null}</div></section>
    {latestYoyo && <section><h2>Ultimo Yo-Yo Test Livello 1</h2><div className="stats"><Stat label="Risultato" value={`${latestYoyo.distance_m} m`} icon={<Activity/>}/><Stat label="Data" value={date(latestYoyo.test_date)} icon={<CalendarDays/>}/><Stat label="Livello" value={latestYoyo.final_level||'—'} icon={<Trophy/>}/></div></section>}{data.leaderboard && <section><h2>Classifica partitelle</h2><div className="stats"><Stat label="Punti" value={data.leaderboard.final_points} icon={<Trophy />} /><Stat label="Vittorie" value={data.leaderboard.wins} icon={<Trophy />} /><Stat label="Pareggi" value={data.leaderboard.draws} icon={<Trophy />} /><Stat label="Sconfitte" value={data.leaderboard.losses} icon={<Trophy />} /></div></section>}
    <section><div className="section-bar"><div><h2>Carico di lavoro</h2><p>Andamento nel periodo selezionato.</p></div></div>{chart.length ? <div className="chart-card"><ResponsiveContainer width="100%" height={280}><LineChart data={chart}><CartesianGrid strokeDasharray="3 3" stroke="#1e344a"/><XAxis dataKey="date" stroke="#6f879d"/><YAxis stroke="#6f879d"/><Tooltip contentStyle={{ background: '#0b1b2d', border: '1px solid #29445f' }}/><Line type="monotone" dataKey="load" stroke="#68e7ff" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></div> : <Empty title="Nessun carico" text="Non ci sono dati di carico nel periodo."/>}</section>
    <section><h2>Partite</h2><div className="cards">{matches.map((m: any) => <div className="info" key={m.match_id}><div><b>{m.opponent}</b><small>{date(m.session_date)} · {m.venue === 'HOME' ? 'Casa' : 'Trasferta'} · {m.home_score ?? 0}-{m.away_score ?? 0}</small></div><span>{m.custom_status || m.callup_status || 'Non indicato'} · {m.started ? 'Titolare' : 'Panchina'} · {m.minutes_played}' · {m.goals} gol</span></div>)}{!matches.length && <div className="panel">Nessuna partita nel periodo.</div>}</div></section>
    <section><h2>Presenze</h2><div className="cards">{attendance.slice(0, 100).map((x: any, i: number) => <div className="info" key={i}><div><b>{date(x.session_date)}</b><small>{x.session_type === 'TRAINING' ? 'Allenamento' : 'Partita'}</small></div><span>{x.status === 'PRESENT' ? 'Presente' : `Assente — ${x.absence_reason || 'Altro'}`}</span></div>)}{!attendance.length && <div className="panel">Nessuna presenza nel periodo.</div>}</div></section>
    <section><h2>Multe</h2><div className="cards">{fines.map((f: any) => <div className="info" key={f.id}><div><b>{money(Number(f.amount))}</b><small>{date(String(f.issued_at).slice(0, 10))}</small></div><span>Pagato {money(Number(f.paid))} · Residuo {money(Number(f.residual))}</span></div>)}{!fines.length && <div className="panel">Nessuna multa nel periodo.</div>}</div></section>
  </div></div>;
}
