import { useEffect, useState } from 'react';
import { Edit3, Plus, Save, SlidersHorizontal, Trash2 } from 'lucide-react';
import { useParams } from 'react-router-dom';
import { supabase } from '../lib/supabase';
import { Page } from '../components/Layout';
import { Center, Confirm, Modal } from '../components/ui';
import { useSeason } from '../hooks/useSeason';
import { useToast } from '../components/Toast';
import { rand } from '../lib/utils';

export default function Settings() {
  const { seasonId } = useParams(), { season, loading } = useSeason(seasonId), toast = useToast();
  const [s, setS] = useState<any>({ win_points: 3, draw_points: 1, loss_points: 0, penalty_mode: 'SUBTRACT', insight_baseline_days: 28, default_training_duration: 90 });
  const [options, setOptions] = useState<any[]>([]), [busy, setBusy] = useState(false), [modal, setModal] = useState(false), [editing, setEditing] = useState<any>(null), [label, setLabel] = useState(''), [confirm, setConfirm] = useState<any>(null);
  async function load() { if (!seasonId) return; const [{ data: settings }, { data: opts }] = await Promise.all([supabase.from('season_settings').select('*').eq('season_id', seasonId).maybeSingle(), supabase.from('callup_status_options').select('*').eq('season_id', seasonId).order('label')]); if (settings) setS(settings); setOptions(opts || []); }
  useEffect(() => { load(); }, [seasonId]);
  async function save(e: React.FormEvent) { e.preventDefault(); setBusy(true); const { error } = await supabase.from('season_settings').upsert({ ...s, season_id: seasonId }, { onConflict: 'season_id' }); if (error) toast.push(error.message, 'error'); else toast.push('Impostazioni salvate'); setBusy(false); }
  function openOption(o: any = null) { setEditing(o); setLabel(o?.label || ''); setModal(true); }
  async function saveOption(e: React.FormEvent) { e.preventDefault(); if (!seasonId || !label.trim()) return; setBusy(true); const res = editing ? await supabase.from('callup_status_options').update({ label: label.trim() }).eq('id', editing.id) : await supabase.from('callup_status_options').insert({ season_id: seasonId, code: `CUSTOM_${rand().slice(0, 10)}`, label: label.trim(), active: true }); if (res.error) toast.push(res.error.message, 'error'); else { toast.push(editing ? 'Stato aggiornato' : 'Stato aggiunto'); setModal(false); await load(); } setBusy(false); }
  async function removeOption() { if (!confirm) return; const { error } = await supabase.from('callup_status_options').delete().eq('id', confirm.id); if (error) toast.push(error.message, 'error'); else { toast.push('Stato eliminato'); await load(); } setConfirm(null); }
  if (loading || !season) return <Center />;
  return <Page season={season} title="Impostazioni" sub="Regole configurabili della stagione"><form className="form panel" onSubmit={save}><div className="section-bar"><div><h2><SlidersHorizontal /> Classifica partitelle</h2><p>Il calcolo predefinito resta 3-1-0, ma può essere personalizzato.</p></div></div><div className="form-grid"><label>Vittoria<input type="number" min="0" max="20" value={s.win_points} onChange={e => setS({ ...s, win_points: Number(e.target.value) })}/></label><label>Pareggio<input type="number" min="0" max="20" value={s.draw_points} onChange={e => setS({ ...s, draw_points: Number(e.target.value) })}/></label><label>Sconfitta<input type="number" min="0" max="20" value={s.loss_points} onChange={e => setS({ ...s, loss_points: Number(e.target.value) })}/></label><label>Penalità<select value={s.penalty_mode} onChange={e => setS({ ...s, penalty_mode: e.target.value })}><option value="SUBTRACT">Sottrai punti</option><option value="IGNORE">Non applicare</option></select></label><label>Baseline insight (giorni)<input type="number" min="7" max="90" value={s.insight_baseline_days} onChange={e => setS({ ...s, insight_baseline_days: Number(e.target.value) })}/></label><label>Durata allenamento predefinita<input type="number" min="0" max="300" value={s.default_training_duration} onChange={e => setS({ ...s, default_training_duration: Number(e.target.value) })}/></label></div><button className="primary" disabled={busy}><Save />{busy ? 'Salvataggio…' : 'Salva impostazioni'}</button></form>
    <section><div className="section-bar"><div><h2>Stati convocazione personalizzati</h2><p>Aggiungi etichette oltre a Convocato, Squalificato, Infortunato, Scelta tecnica e Altro.</p></div><button className="primary" onClick={() => openOption()}><Plus />Nuovo stato</button></div>{options.length ? <div className="cards">{options.map(o => <div className="info" key={o.id}><div><b>{o.label}</b><small>Stato personalizzato</small></div><div className="row-actions"><button className="small" onClick={() => openOption(o)}><Edit3 size={14}/>Modifica</button><button className="icon danger-icon" onClick={() => setConfirm(o)}><Trash2 size={16}/></button></div></div>)}</div> : <div className="panel">Nessuno stato personalizzato. Puoi aggiungere, ad esempio, “Lavoro” o “Permesso”.</div>}</section>
    <div className="panel methodology"><h2>Logica carichi</h2><p>Il carico interno principale è session-RPE: RPE × durata in minuti. L’app usa confronti descrittivi tra periodi e non assegna automaticamente soglie cliniche o rischio infortunio.</p><p className="muted">Gli insight indicano sempre stato, interpretazione, attenzione e suggerimento operativo senza trasformare una variazione di carico in una diagnosi.</p></div>
    {modal && <Modal title={editing ? 'Modifica stato' : 'Nuovo stato'} close={() => setModal(false)}><form className="form" onSubmit={saveOption}><label>Nome dello stato<input autoFocus required value={label} onChange={e => setLabel(e.target.value)} placeholder="Es. Lavoro"/></label><button className="primary wide" disabled={busy}>{busy ? 'Salvataggio…' : 'Salva stato'}</button></form></Modal>}
    {confirm && <Confirm title="Eliminare lo stato personalizzato?" text="Lo stato non sarà più disponibile nelle nuove convocazioni. I dati storici già salvati restano invariati." confirmLabel="Elimina" danger onClose={() => setConfirm(null)} onConfirm={removeOption}/>}</Page>;
}
